//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ws28Entities : DbContext
    {
        public ws28Entities()
            : base("name=ws28Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vxod> Vxod { get; set; }
        public virtual DbSet<tv> tv { get; set; }
        public virtual DbSet<Ty> Ty { get; set; }
        public virtual DbSet<Yac> Yac { get; set; }
    }
}
