//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tv
    {
        public int Id_t { get; set; }
        public string Nazv { get; set; }
        public string Cena { get; set; }
        public string Brend { get; set; }
        public string Harki { get; set; }
        public string Visota { get; set; }
        public string Shirina { get; set; }
        public string Glubina { get; set; }
        public Nullable<int> Id_Type { get; set; }
        public Nullable<int> Id_Ya { get; set; }
    
        public virtual Yac Yac { get; set; }
        public virtual Ty Ty { get; set; }
    }
}
